---
adminUser: admin
adminPassword: admin
grafana.ini:
  server:
    domain: gke.devopstar.com
    root_url: '%(protocol)s://%(domain)s/grafana/'
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
  datasources:
    enabled: true
    label: grafana_datasource
---
