apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  nginx: |
    events {
        worker_connections  1024;
    }

    http {
        server {
            listen 8080;

            location /hosting/ {
                root /data/www;
                rewrite ^/hosting/(.*) /$1 break;
            }
        }
    }
  nginx-dashboard: |+{{ range .Files.Lines "nginx-dashboard.json" }}
    {{ . }}{{ end }}
